[package]
authors = ["messense <messense@icloud.com>"]
name = "badwolf-runner"
version = "0.1.0"

[dependencies]
yaml-rust = "0.3.0"

[lib]
name = "badwolf_runner"
path = "src/lib.rs"

[[bin]]
name = "badwolf-run"
path = "src/main.rs"
